version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app

# 이렇게 주석처리하면 mysql 셋팅은 빼고 실행하기 때문에 폴더는 그냥 놔둬도 됨
#  mysql:
#    build: ./mysql
#    restart: unless-stopped
#    container_name: app_mysql
#    ports:
#      - "3307:3307"
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql
#      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#    environment:
#      MYSQL_ROOT_PASSWORD: 123qwe!
#      MYSQL_DATABASE: myapp

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app_nginx
    ports:
      - "3000:80"
